volumes:
  adventure-data:
    external: true
services:
  react:
    image: node:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./react-1/app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
  destination_api:
    build:
      context: ./destination/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8100:8000"
    volumes:
      - ./destination/api:/app
  accommodation_api:
    build:
      context: ./accommodation/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./accommodation/api:/app
  accommodation_poller:
    build:
      context: ./accommodation/poll
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./accommodation/poll:/app
      - ./accommodation/api/accommodation_project:/app/accommodation_project
      - ./accommodation/api/accommodation_rest:/app/accommodation_rest
    depends_on:
      - accommodation_api
  things_to_do_api:
    build:
      context: ./things_to_do/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./things_to_do/api:/app
  things_to_do_poller:
    build:
      context: ./things_to_do/poll
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./things_to_do/poll:/app
      - ./things_to_do/api/things_to_do_project:/app/things_to_do_project
      - ./things_to_do/api/things_to_do_rest:/app/things_to_do_rest
    depends_on:
      - things_to_do_api
