volumes:
  adventure-data:
    external: true
services:
  destination_api:
    build:
      context: ./destination/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8100:8000"
    volumes:
      - ./destination/api:/app
    environment:
      DATABASE_URL: postgres://destination:password@database:5432/destination
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
  accommodation_api:
    build:
      context: ./accommodation/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./accommodation/api:/app
    environment:
      DATABASE_URL: postgres://accommodation:password@database:5432/accommodation
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT:
  accommodation_poller:
    build:
      context: ./accommodation/poll
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./accommodation/poll:/app
      - ./accommodation/api/accommodation_project:/app/accommodation_project
      - ./accommodation/api/accommodation_rest:/app/accommodation_rest
    depends_on:
      - accommodation_api
    environment:
      DATABASE_URL: postgres://accommodation:password@database:5432/accommodation
      WAIT_HOSTS: database:5432, accommodation_api:8000
      WAIT_TIMEOUT: 240
  things_to_do_api:
    build:
      context: ./things_to_do/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./things_to_do/api:/app
    environment:
      DATABASE_URL: postgres://things_to_do:password@database:5432/things_to_do
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
  things_to_do_poller:
    build:
      context: ./things_to_do/poll
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./things_to_do/poll:/app
      - ./things_to_do/api/things_to_do_project:/app/things_to_do_project
      - ./things_to_do/api/things_to_do_rest:/app/things_to_do_rest
    depends_on:
      - things_to_do_api
    environment:
      DATABASE_URL: postgres://things_to_do:password@database:5432/things_to_do
      WAIT_HOSTS: database:5432,things_to_do_api:8000
      WAIT_TIMEOUT: 240
